### ISSUE TITLE
Seems to require Google Tag Manager

### ISSUE THREAD

**Issue by anthonygore** [nuxt-community/google-optimize#20]
I struggled to get this working but eventually figured it out. I couldn't see this anywhere in the docs, but I had to add the container ID using Google Tag Manager. It's simple enough with the Nuxt module:

```
modules: [
   ['@nuxtjs/google-tag-manager', { id: 'your-container-id' }],
]
```

I have not looked into this deeply, so maybe my case is a one-off, or maybe this belongs in the docs, I dunno.

**Comment by RanKey1496** [comment]
I still have doubts
