### ISSUE TITLE
Run multiple experiments simultaneously

### ISSUE THREAD

**Issue by yaelp2** [nuxt-community/google-optimize#22]
Is it possible to run multiple experiments simultaneously?
As I see in the source code, if I create multiple experiments it randomly chooses only one based on the experiments weight.
Is there a way to run 2 experiments at the same time? i.e $exp will contain array of experiments where each experiment contains its active variant

Thanks in advanced,
Yael, Full-Stack Developer

**Comment by farzadso** [comment]
@yaelp2 Right now the module only allows running on experiment as it stores the initially elected experiment in the cookie. We do plan on making it support multiple experiments at the same time but there are a few caveats, e.g. running two experiments in the same page is kind of weird if they have the same effect.
PRs are welcome.
