### ISSUE TITLE
The usage of the module is not clear

### ISSUE THREAD

**Issue by ahndohun** [nuxt-community/google-optimize#25]
I'm trying to understand how the module works.
You have completed setting up the project correctly and confirmed that the experiment is activated in the development environment.
However, it seems to work independently from the Google Optimized settings.
When I actually deployed and started the Google Optimizer experiment, I didn't see the results I wanted in the preview.
Thank you for letting me know what I'm missing.

**Comment by farzadso** [comment]
@ahndohun Sorry for the late reply. Did you find what you were looking for?

**Comment by RanKey1496** [comment]
I still have doubts

**Comment by farzadso** [comment]
@RanKey1496 Can I help clear those doubts?
